spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/alkis_data}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 120000
      idleTimeout: 600000
      maxLifetime: 1800000
      auto-commit: false
      maximum-pool-size: 4
      minimum-idle: 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL

ftp:
  host: 185.138.42.187
  username: alkis
  password: ${FTP_SAKITO_PASSWORD}
  directory: ""
  connect_timeout: 60000
  default_timeout: 60000
  data_timeout: 60000